# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  matrix:
    - DJANGO=1.8.13 CMS=3.4.4
    - DJANGO=1.9.7 CMS=3.4.4
    - DJANGO=1.10.8 CMS=3.4.4

install:
  - pip install -r requirements-test.txt
  - pip install -q Django==$DJANGO
  - pip install -q django-cms==$CMS
  - python setup.py install

script:
  - coverage run $(which djangocms-helper) djangocms_ss_icon test --cms

after_success: coveralls
