# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_ss_icon_icon', serialize=False, to='cms.CMSPlugin')),
                ('icon', models.CharField(choices=[('fa-facebook', 'facebook'), ('fa-foursquare', 'foursquare'), ('fa-google-plus', 'google-plus'), ('fa-instagram', 'instagram'), ('fa-linkedin', 'linkedin'), ('fa-twitter', 'twitter'), ('fa-xing', 'xing'), ('fa-yelp', 'yelp'), ('fa-youtube-play', 'youtube'), ('fa-spinner', 'Spinner'), ('fa-refresh', 'Refresh'), ('fa-cog', 'Cog')], max_length=255, verbose_name='Icon')),
                ('size', models.CharField(blank=True, choices=[(None, 'Standard'), ('fa-lg', 'Large'), ('fa-2x', '2x Large'), ('fa-2x', '3x Large'), ('fa-2x', '4x Large'), ('fa-2x', '5x Large')], max_length=5, null=True, verbose_name='Size')),
                ('fixed_width', models.BooleanField(default=False, verbose_name='Fixed Width')),
                ('spin', models.BooleanField(default=False, help_text='Icon will rotate smoothly.  Works well with spinner, refresh, cog', verbose_name='Spin')),
                ('pulse', models.BooleanField(default=False, help_text='Icon will rotate with 8 steps.  Works well with spinner, refresh, cog', verbose_name='Pulse')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
